### PR TITLE
Rewrite the PreRegisterVerifierController to use annotations

### PR DESCRIPTION
**Pull request by wjam**

### CODE REVIEW

**Comment by kittylyst** [comment]
Personally, I have no issue with this, but this does use random data at one point, making the test runs technically non-deterministic. As a general style issue, are we happy that this is OK? Leaving open for now - anyone who feels strongly, please comment.

**Comment by wjam** [comment]
I feel that it keeps you honest as you could otherwise implement the class just by using the same hardcoded values rather than the real parameters. It also avoids me having to come up with realistic test data without resorting to 'test' yet again.

**Comment by njacobs5074** [comment]
If we run multiple, simultaneous instances of the integration tests, does
that work?  I've mostly seen issues with random data when there was a
shared middle tier for integration tests because often random data is only
pseudo-random.

I realize that it's not an immediate issue, but if we start running this
code on a CI platform where we could be running the same test
simultaneously, we'd need to be aware of this arrangement.

Nick



On Sun, Mar 1, 2015 at 2:47 PM, Will May <notifications@github.com> wrote:

> I feel that it keeps you honest as you could otherwise implement the class
> just by using the same hardcoded values rather than the real parameters. It
> also avoids me having to come up with realistic test data without resorting
> to 'test' yet again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kittylyst/VillagePaymentAgent/pull/57#issuecomment-76599825>
> .
>



-- 
Phone: +44 7463 853 913
LinkedIn: http://uk.linkedin.com/in/njacobs5074
Twitter: @njacobs5074

**Comment by kittylyst** [comment]
It should still work, as these tests are small enough, but at integration scale, we'd need to be aware of it. As no-one's stronlgy arguing against this, I'll merge - but flag Nick's comments to remind us to proceed with caution when we get to more integration tests.

**Pull request merged**
